GRANT USAGE ON SCHEMA nexus TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA nexus TO service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA nexus TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA nexus TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA nexus GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA nexus GRANT ALL ON ROUTINES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA nexus GRANT ALL ON SEQUENCES TO service_role;

GRANT USAGE ON SCHEMA tba TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA tba TO service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA tba TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tba TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tba GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tba GRANT ALL ON ROUTINES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tba GRANT ALL ON SEQUENCES TO service_role;
